# Generated by Django 5.0.6 on 2024-05-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negativeminingresult',
            name='model_checkpoint',
            field=models.CharField(default='default_value', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='negativeminingresult',
            name='model_name',
            field=models.CharField(default='default_value', max_length=255),
            preserve_default=False,
        ),
    ]
