# Generated by Django 5.0.6 on 2024-05-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_alter_negativeminingresult_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('loss_path', models.CharField(default='default', max_length=255)),
                ('checkpoint_paths', models.CharField(default='default', max_length=2000)),
                ('status', models.CharField(default='Training', max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='negativeminingresult',
            old_name='config',
            new_name='status',
        ),
    ]
